In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

In [2]:
from imblearn.under_sampling import ClusterCentroids #undersampling
from imblearn.over_sampling import SMOTE  #oversampling
from imblearn.combine import SMOTEENN

C:\Users\zweiv_000\Anaconda\Lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
%matplotlib inline
df = pd.read_csv("D:\\Study\\Kaggle\\Creditcard\\creditcardfraud\\creditcard.csv")

In [4]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  3.919560e-15  5.688174e-16 -8.769071e-15  2.782312e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean  -1.552563e-15  2.010663e-15 -1.694249e-15 -1.927028e-16 -3.137024e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

           ...                 V21           V22           V23           V24  \
count      ...        2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean       ...        1.537294e-16  7.959909e-16  5.367590e-16  4.458112e-15   
std        ...        7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min        ...       -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%        ...       -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%        ...       -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%        ...        1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max        ...        2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   1.453003e-15  1.699104e-15 -3.660161e-16 -1.206049e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [5]:
print(df['Class'].value_counts())

0    284315
1       492
dtype: int64


In [6]:
from sklearn.cross_validation import train_test_split

In [7]:
train, test = train_test_split(df, train_size = 0.8)

In [8]:
train.head()

Time        V1        V2        V3        V4        V5        V6  \
232034  147018  2.061914 -0.930685 -1.332030 -0.836660 -0.674025 -1.131098   
99435    67117 -1.208470  0.951165 -0.244983  0.223672  2.079472  3.976262   
73849    55307  1.154786  0.182814  0.361292  0.585828 -0.321323 -0.419634   
248956  154172  0.439804  1.343752 -1.364688  1.309440  0.340152 -0.412269   
214804  139828  2.101790  0.620181 -2.669859  0.595129  0.956859 -1.365729   

              V7        V8        V9  ...         V21       V22       V23  \
232034 -0.274863 -0.250526 -0.628454  ...    0.109007  0.154640  0.151933   
99435  -0.061037  1.247319 -0.716606  ...   -0.080990 -0.355521 -0.454210   
73849  -0.161868  0.129509 -0.083158  ...   -0.207098 -0.653243  0.184159   
248956  0.200711  0.159247 -0.200281  ...   -0.106938 -0.260220  0.356932   
214804  0.407762 -0.403228  0.453760  ...    0.056062  0.403919 -0.148900   

             V24       V25       V26       V27       V28  Amount  Class  
232034  0.068731 -0.102820 -0.307580 -0.059521 -0.064368   68.23      0  
99435   1.035642  0.654601 -0.168048 -0.204980 -0.094336   64.54      0  
73849   0.154760  0.049876  0.097625 -0.017159  0.017032    1.98      0  
248956  0.504631 -1.333203 -0.386510 -0.186872  0.049028    9.99      0  
214804 -0.911090  0.382023 -0.058342  0.023708  0.001718    1.00      0  

[5 rows x 31 columns]

In [11]:
train_label = train["Class"]
train_label
train_feature = train.drop("Class", axis = 1)

In [12]:
train_feature.head()

Time        V1        V2        V3        V4        V5        V6  \
232034  147018  2.061914 -0.930685 -1.332030 -0.836660 -0.674025 -1.131098   
99435    67117 -1.208470  0.951165 -0.244983  0.223672  2.079472  3.976262   
73849    55307  1.154786  0.182814  0.361292  0.585828 -0.321323 -0.419634   
248956  154172  0.439804  1.343752 -1.364688  1.309440  0.340152 -0.412269   
214804  139828  2.101790  0.620181 -2.669859  0.595129  0.956859 -1.365729   

              V7        V8        V9   ...         V20       V21       V22  \
232034 -0.274863 -0.250526 -0.628454   ...    0.015613  0.109007  0.154640   
99435  -0.061037  1.247319 -0.716606   ...   -0.037298 -0.080990 -0.355521   
73849  -0.161868  0.129509 -0.083158   ...   -0.176027 -0.207098 -0.653243   
248956  0.200711  0.159247 -0.200281   ...    0.049756 -0.106938 -0.260220   
214804  0.407762 -0.403228  0.453760   ...   -0.084654  0.056062  0.403919   

             V23       V24       V25       V26       V27       V28  Amount  
232034  0.151933  0.068731 -0.102820 -0.307580 -0.059521 -0.064368   68.23  
99435  -0.454210  1.035642  0.654601 -0.168048 -0.204980 -0.094336   64.54  
73849   0.184159  0.154760  0.049876  0.097625 -0.017159  0.017032    1.98  
248956  0.356932  0.504631 -1.333203 -0.386510 -0.186872  0.049028    9.99  
214804 -0.148900 -0.911090  0.382023 -0.058342  0.023708  0.001718    1.00  

[5 rows x 30 columns]

In [13]:
CC = ClusterCentroids()
ccx, ccy = CC.fit_sample(train_feature, train_label)


0    227451
1       394
dtype: int64


In [16]:
unique, counts = np.unique(ccy, return_counts=True)
print np.asarray((unique, counts)).T

[[  0 394]
 [  1 394]]


In [25]:
test_label = test["Class"]
test_label
test_feature = test.drop("Class", axis = 1)

In [27]:
rfc = RandomForestClassifier()
rfc.fit(ccx,ccy)
y_cc_pred = rfc.predict(test_feature) 

print(classification_report(y_cc_pred,test_label))

             precision    recall  f1-score   support

          0       0.16      1.00      0.28      9278
          1       1.00      0.00      0.00     47684

avg / total       0.86      0.16      0.05     56962



In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_label, y_cc_pred)

array([[ 9278, 47586],
       [    0,    98]])

In [33]:
smote = SMOTE(ratio='auto', kind='regular')
smox, smoy = smote.fit_sample(train_feature, train_label)

In [34]:
unique_smote, counts_smote = np.unique(smoy, return_counts=True)
print np.asarray((unique_smote, counts_smote)).T

[[     0 227451]
 [     1 227451]]


In [35]:
rfc.fit(smox,smoy)
y_smote_pred = rfc.predict(test_feature) 
print(classification_report(y_smote_pred,test_label))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     56866
          1       0.87      0.89      0.88        96

avg / total       1.00      1.00      1.00     56962



In [36]:
confusion_matrix(test_label, y_smote_pred)

array([[56853,    11],
       [   13,    85]])

In [40]:
SENN = SMOTEENN(ratio = 'auto')
ennx, enny = SENN.fit_sample(train_feature, train_label)
unique_enny, counts_enny = np.unique(enny, return_counts=True)
print np.asarray((unique_enny, counts_enny)).T

[[     0 227451]
 [     1 217857]]


In [41]:
rfc.fit(ennx, enny)
y_senn_pred = rfc.predict(test_feature) 
print(classification_report(y_senn_pred,test_label))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     56858
          1       0.88      0.83      0.85       104

avg / total       1.00      1.00      1.00     56962



In [42]:
confusion_matrix(test_label, y_senn_pred)

array([[56846,    18],
       [   12,    86]])